"use client";
import { lazy, Suspense } from "react";
const charts = {
  "chart-area-axes": lazy(() => import("./chart-area-axes").then(m => ({ default: m.ChartAreaAxes }))),
  "chart-area-default": lazy(() => import("./chart-area-default").then(m => ({ default: m.ChartAreaDefault }))),
  "chart-area-gradient": lazy(() => import("./chart-area-gradient").then(m => ({ default: m.ChartAreaGradient }))),
  "chart-area-icons": lazy(() => import("./chart-area-icons").then(m => ({ default: m.ChartAreaIcons }))),
  "chart-area-interactive": lazy(() => import("./chart-area-interactive").then(m => ({ default: m.ChartAreaInteractive }))),
  "chart-area-legend": lazy(() => import("./chart-area-legend").then(m => ({ default: m.ChartAreaLegend }))),
  "chart-area-linear": lazy(() => import("./chart-area-linear").then(m => ({ default: m.ChartAreaLinear }))),
  "chart-area-stacked-expand": lazy(() => import("./chart-area-stacked-expand").then(m => ({ default: m.ChartAreaStackedExpand }))),
  "chart-area-stacked": lazy(() => import("./chart-area-stacked").then(m => ({ default: m.ChartAreaStacked }))),
  "chart-area-step": lazy(() => import("./chart-area-step").then(m => ({ default: m.ChartAreaStep }))),
  "chart-bar-active": lazy(() => import("./chart-bar-active").then(m => ({ default: m.ChartBarActive }))),
  "chart-bar-default": lazy(() => import("./chart-bar-default").then(m => ({ default: m.ChartBarDefault }))),
  "chart-bar-horizontal": lazy(() => import("./chart-bar-horizontal").then(m => ({ default: m.ChartBarHorizontal }))),
  "chart-bar-interactive": lazy(() => import("./chart-bar-interactive").then(m => ({ default: m.ChartBarInteractive }))),
  "chart-bar-label-custom": lazy(() => import("./chart-bar-label-custom").then(m => ({ default: m.ChartBarLabelCustom }))),
  "chart-bar-label": lazy(() => import("./chart-bar-label").then(m => ({ default: m.ChartBarLabel }))),
  "chart-bar-mixed": lazy(() => import("./chart-bar-mixed").then(m => ({ default: m.ChartBarMixed }))),
  "chart-bar-multiple": lazy(() => import("./chart-bar-multiple").then(m => ({ default: m.ChartBarMultiple }))),
  "chart-bar-negative": lazy(() => import("./chart-bar-negative").then(m => ({ default: m.ChartBarNegative }))),
  "chart-bar-stacked": lazy(() => import("./chart-bar-stacked").then(m => ({ default: m.ChartBarStacked }))),
  "chart-line-default": lazy(() => import("./chart-line-default").then(m => ({ default: m.ChartLineDefault }))),
  "chart-line-dots-colors": lazy(() => import("./chart-line-dots-colors").then(m => ({ default: m.ChartLineDotsColors }))),
  "chart-line-dots-custom": lazy(() => import("./chart-line-dots-custom").then(m => ({ default: m.ChartLineDotsCustom }))),
  "chart-line-dots": lazy(() => import("./chart-line-dots").then(m => ({ default: m.ChartLineDots }))),
  "chart-line-interactive": lazy(() => import("./chart-line-interactive").then(m => ({ default: m.ChartLineInteractive }))),
  "chart-line-label-custom": lazy(() => import("./chart-line-label-custom").then(m => ({ default: m.ChartLineLabelCustom }))),
  "chart-line-label": lazy(() => import("./chart-line-label").then(m => ({ default: m.ChartLineLabel }))),
  "chart-line-linear": lazy(() => import("./chart-line-linear").then(m => ({ default: m.ChartLineLinear }))),
  "chart-line-multiple": lazy(() => import("./chart-line-multiple").then(m => ({ default: m.ChartLineMultiple }))),
  "chart-line-step": lazy(() => import("./chart-line-step").then(m => ({ default: m.ChartLineStep }))),
  "chart-pie-donut-active": lazy(() => import("./chart-pie-donut-active").then(m => ({ default: m.ChartPieDonutActive }))),
  "chart-pie-donut-text": lazy(() => import("./chart-pie-donut-text").then(m => ({ default: m.ChartPieDonutText }))),
  "chart-pie-donut": lazy(() => import("./chart-pie-donut").then(m => ({ default: m.ChartPieDonut }))),
  "chart-pie-interactive": lazy(() => import("./chart-pie-interactive").then(m => ({ default: m.ChartPieInteractive }))),
  "chart-pie-label-custom": lazy(() => import("./chart-pie-label-custom").then(m => ({ default: m.ChartPieLabelCustom }))),
  "chart-pie-label-list": lazy(() => import("./chart-pie-label-list").then(m => ({ default: m.ChartPieLabelList }))),
  "chart-pie-label": lazy(() => import("./chart-pie-label").then(m => ({ default: m.ChartPieLabel }))),
  "chart-pie-legend": lazy(() => import("./chart-pie-legend").then(m => ({ default: m.ChartPieLegend }))),
  "chart-pie-separator-none": lazy(() => import("./chart-pie-separator-none").then(m => ({ default: m.ChartPieSeparatorNone }))),
  "chart-pie-simple": lazy(() => import("./chart-pie-simple").then(m => ({ default: m.ChartPieSimple }))),
  "chart-pie-stacked": lazy(() => import("./chart-pie-stacked").then(m => ({ default: m.ChartPieStacked }))),
  "chart-radar-default": lazy(() => import("./chart-radar-default").then(m => ({ default: m.ChartRadarDefault }))),
  "chart-radar-dots": lazy(() => import("./chart-radar-dots").then(m => ({ default: m.ChartRadarDots }))),
  "chart-radar-grid-circle-fill": lazy(() => import("./chart-radar-grid-circle-fill").then(m => ({ default: m.ChartRadarGridCircleFill }))),
  "chart-radar-grid-circle-no-lines": lazy(() => import("./chart-radar-grid-circle-no-lines").then(m => ({ default: m.ChartRadarGridCircleNoLines }))),
  "chart-radar-grid-circle": lazy(() => import("./chart-radar-grid-circle").then(m => ({ default: m.ChartRadarGridCircle }))),
  "chart-radar-grid-custom": lazy(() => import("./chart-radar-grid-custom").then(m => ({ default: m.ChartRadarGridCustom }))),
  "chart-radar-grid-fill": lazy(() => import("./chart-radar-grid-fill").then(m => ({ default: m.ChartRadarGridFill }))),
  "chart-radar-grid-none": lazy(() => import("./chart-radar-grid-none").then(m => ({ default: m.ChartRadarGridNone }))),
  "chart-radar-icons": lazy(() => import("./chart-radar-icons").then(m => ({ default: m.ChartRadarIcons }))),
  "chart-radar-label-custom": lazy(() => import("./chart-radar-label-custom").then(m => ({ default: m.ChartRadarLabelCustom }))),
  "chart-radar-legend": lazy(() => import("./chart-radar-legend").then(m => ({ default: m.ChartRadarLegend }))),
  "chart-radar-lines-only": lazy(() => import("./chart-radar-lines-only").then(m => ({ default: m.ChartRadarLinesOnly }))),
  "chart-radar-multiple": lazy(() => import("./chart-radar-multiple").then(m => ({ default: m.ChartRadarMultiple }))),
  "chart-radar-radius": lazy(() => import("./chart-radar-radius").then(m => ({ default: m.ChartRadarRadius }))),
  "chart-radial-grid": lazy(() => import("./chart-radial-grid").then(m => ({ default: m.ChartRadialGrid }))),
  "chart-radial-label": lazy(() => import("./chart-radial-label").then(m => ({ default: m.ChartRadialLabel }))),
  "chart-radial-shape": lazy(() => import("./chart-radial-shape").then(m => ({ default: m.ChartRadialShape }))),
  "chart-radial-simple": lazy(() => import("./chart-radial-simple").then(m => ({ default: m.ChartRadialSimple }))),
  "chart-radial-stacked": lazy(() => import("./chart-radial-stacked").then(m => ({ default: m.ChartRadialStacked }))),
  "chart-radial-text": lazy(() => import("./chart-radial-text").then(m => ({ default: m.ChartRadialText }))),
  "chart-tooltip-default": lazy(() => import("./chart-tooltip-default").then(m => ({ default: m.ChartTooltipDefault }))),
  "chart-tooltip-indicator-line": lazy(() => import("./chart-tooltip-indicator-line").then(m => ({ default: m.ChartTooltipIndicatorLine }))),
  "chart-tooltip-indicator-none": lazy(() => import("./chart-tooltip-indicator-none").then(m => ({ default: m.ChartTooltipIndicatorNone }))),
  "chart-tooltip-label-none": lazy(() => import("./chart-tooltip-label-none").then(m => ({ default: m.ChartTooltipLabelNone }))),
  "chart-tooltip-label-custom": lazy(() => import("./chart-tooltip-label-custom").then(m => ({ default: m.ChartTooltipLabelCustom }))),
  "chart-tooltip-label-formatter": lazy(() => import("./chart-tooltip-label-formatter").then(m => ({ default: m.ChartTooltipLabelFormatter }))),
  "chart-tooltip-formatter": lazy(() => import("./chart-tooltip-formatter").then(m => ({ default: m.ChartTooltipFormatter }))),
  "chart-tooltip-icons": lazy(() => import("./chart-tooltip-icons").then(m => ({ default: m.ChartTooltipIcons }))),
  "chart-tooltip-advanced": lazy(() => import("./chart-tooltip-advanced").then(m => ({ default: m.ChartTooltipAdvanced }))),
};
export function ShadcnChartPreview({ name }: { name: string }) {
 const Chart = charts[name as keyof typeof charts];
 return Chart ? <Suspense fallback={<p>加载图表…</p>}><Chart /></Suspense> : null;
}
